CREATE TABLE "mytable" (
  "CREATE DATABASE najd_delights;" text NULL
);

INSERT INTO "mytable" ("CREATE DATABASE najd_delights;")
VALUES
('show databases;'),
('USE najd_delights;'),
('CREATE TABLE Staff ('),
('Staff_ID int'),
('Fname VARCHAR(60)'),
('Lname VARCHAR(60)'),
('phone VARCHAR(20)'),
('role ENUM(''Chef'''),
(');'),
('describe Staff;'),
('CREATE TABLE Orders ('),
('Order_ID int'),
('Customer_ID INT'),
('Staff_ID int'),
('Order_Date DATETIME'),
('Order_Type ENUM(''Dine_in'''),
('Payment_Method ENUM(''cash'''),
('Total_Amount DECIMAL(8'),
(');'),
('describe Orders;'),
('CREATE TABLE Dish ('),
('Dish_ID INT'),
('Dish_Name VARCHAR(100)'),
('Category ENUM(''Appetizer'''),
('Price DECIMAL(6'),
(');'),
('describe Dish;'),
('CREATE TABLE Order_Details ('),
('Order_ID INT'),
('Dish_ID INT'),
('Quantity INT'),
(');'),
('describe Order_Details;'),
('CREATE TABLE Customer ('),
('Customer_ID INT'),
('Fname VARCHAR(60)'),
('Lname VARCHAR(60)'),
('Phone VARCHAR(20)'),
(');'),
('describe Customer;'),
('show tables;'),
('alter table Customer'),
('ADD Email  VARCHAR(100);'),
('alter table Customer'),
('rename column phone to phone_number;'),
('alter table Customer'),
('modify column phone_number VARCHAR(10);'),
('describe Customer;'),
('alter table Customer'),
('drop column Email;'),
('INSERT INTO Customer (Customer_ID'),
('Phone_Number) VALUES (1'),
(NULL),
('INSERT INTO Customer VALUES (2'),
('''0569876543'');'),
('INSERT INTO Customer VALUES (3'),
('(4'),
('drop table Staff;'),
('CREATE TABLE Staff ('),
('Staff_ID int'),
('Fname VARCHAR(60)'),
('Lname VARCHAR(60)'),
('phone VARCHAR(20)'),
('role ENUM(''Chef'''),
(');'),
('INSERT INTO Staff VALUES'),
('(1'),
('(2'),
('(3'),
('(4'),
('INSERT INTO Dish VALUES'),
('(1'),
('(2'),
('(3'),
('(4'),
('INSERT INTO Orders VALUES'),
('(1'),
('(2'),
('(3'),
('(4'),
('INSERT INTO Order_Details VALUES'),
('(1'),
('(1'),
('(2'),
('(2'),
('(3'),
('(3'),
('(4'),
('SELECT * FROM Customer;'),
('SELECT Fname'),
('FROM Staff;'),
('SELECT Dish_Name'),
('WHERE Price < 15;'),
('UPDATE Customer'),
('SET phone_number = ''050000111'''),
('WHERE Customer_ID = 3;'),
('select Fname'),
('WHERE Customer_ID = 3;'),
('DELETE FROM Staff'),
('WHERE Staff_ID =2;'),
(NULL),
('SELECT * FROM Staff;'),
(NULL),
('SELECT * FROM Order_Details;'),
('DELETE FROM Dish;'),
('SELECT * FROM Dish;'),
(NULL),
('DELETE FROM Staff;'),
('DELETE FROM Customer;'),
('ALTER TABLE Customer'),
('ADD PRIMARY KEY (Customer_ID);'),
('describe Customer;'),
('ALTER TABLE Staff'),
('ADD PRIMARY KEY (Staff_ID);'),
('describe Staff;'),
('ALTER TABLE Orders'),
('ADD FOREIGN KEY (Customer_ID) REFERENCES'),
('Customer(Customer_ID);'),
('describe Orders;'),
('ALTER TABLE Customer'),
('MODIFY COLUMN Fname VARCHAR(100) NOT NULL'),
('MODIFY COLUMN Lname VARCHAR(100) NOT NULL'),
('MODIFY COLUMN Phone_Number VARCHAR(10) NOT NULL;'),
('ALTER TABLE Staff'),
('MODIFY COLUMN Fname VARCHAR(60) NOT NULL'),
('MODIFY COLUMN Lname VARCHAR(60) NOT NULL'),
('MODIFY COLUMN phone VARCHAR(20) NOT NULL;'),
('ALTER TABLE Customer'),
('ADD UNIQUE (Phone_number);'),
('ALTER TABLE Dish'),
('ADD CHECK (Price > 0);'),
('INSERT INTO Dish VALUES (1'),
('describe Dish;'),
('ALTER TABLE Orders'),
('Alter Payment_Method SET DEFAULT ''Card'';'),
('SELECT MIN(Total_Amount) AS min_order'),
('FROM Orders WHERE Order_Type = ''Dine_in'';'),
('SELECT MAX(Total_Amount) AS max_order'),
('FROM Orders;'),
('SELECT COUNT(*) AS total_orders'),
('FROM Orders;'),
('SELECT COUNT(Order_Type) AS takeaway_orders'),
('FROM Orders'),
('WHERE Order_Type = ''takeaway'';'),
('SELECT COUNT(DISTINCT Customer_ID) AS customers'),
('FROM Orders;'),
('SELECT SUM(Quantity) AS total_dishes_sold'),
('FROM Order_Details;'),
('describe Order_Details;'),
('SELECT AVG(Total_Amount) AS avg_order_value'),
('FROM Orders;'),
('SELECT Role'),
('FROM Staff'),
('GROUP BY Role;'),
('ALTER TABLE Orders'),
('ADD PRIMARY KEY (Order_ID);'),
('ALTER TABLE Dish'),
('ADD PRIMARY KEY (Dish_ID);'),
('ALTER TABLE Order_Details'),
('ADD FOREIGN KEY (Order_ID) REFERENCES Orders(Order_ID);'),
('ALTER TABLE Order_Details'),
('ADD FOREIGN KEY (Dish_ID) REFERENCES Dish(Dish_ID);'),
('ALTER TABLE Orders'),
('ADD FOREIGN KEY (Staff_ID) REFERENCES Staff(Staff_ID);'),
('ALTER TABLE Order_Details'),
('ADD CHECK (Quantity > 0);'),
('ALTER TABLE Orders'),
('ADD CHECK (Total_Amount >= 0);'),
('DESCRIBE Orders;'),
('DESCRIBE Dish;'),
('DESCRIBE Order_Details;'),
('SELECT * FROM Orders;'),
('SELECT * FROM Dish;'),
('SELECT * FROM Staff;'),
('SELECT * FROM Customer;'),
('SELECT * FROM Order_Details;');
